"""Agrega fecha_venta a ventas

Revision ID: 1e5c42b7f38f
Revises: 
Create Date: 2026-02-25 18:42:43.431053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5c42b7f38f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_venta', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('total')
        batch_op.drop_column('fecha_venta')

    # ### end Alembic commands ###
